version: '3.8'

services:
  server:
    image: faculty_appraisal_backend:latest
    container_name: faculty_appraisal_backend
    restart: unless-stopped
    ports:
      - "8000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app

