version: '3.8'

services:
  server:
    image: faculty_appraisal_backend:test
    container_name: faculty_appraisal_backend_test
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./uploads_test:/app/uploads_test
    env_file:
      - .env.test
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - PORT=8002
      - TESTING=True
      - ENV_FILE=.env.test

