version: '3.8'

services:
  server:
    image: faculty_appraisal_backend:test
    container_name: faculty_appraisal_backend_test
    restart: unless-stopped
    ports:
      - "8002:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./uploads_test:/app/uploads_test
    env_file:
      - .env.test
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app

