"""initial_schema

Revision ID: 7c2cdbc683ef
Revises: 
Create Date: 2026-08-16 13:46:14.093789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = '7c2cdbc683ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def safe_create_table(name, *args, **kwargs):
    from alembic import context
    if context.is_offline_mode():
        getattr(op, "create_table")(name, *args, **kwargs)
        return
    conn = op.get_bind()
    import sqlalchemy as sa
    inspector = sa.inspect(conn)
    if name not in inspector.get_table_names():
        getattr(op, "create_table")(name, *args, **kwargs)
    else:
        # Table exists. Self-heal by adding any missing columns.
        existing_cols = {c["name"] for c in inspector.get_columns(name)}
        for arg in args:
            if isinstance(arg, sa.Column):
                if arg.name not in existing_cols:
                    op.add_column(name, arg)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    safe_create_table('acr_scores',
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('alumni_engagement',
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('activity', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('announcements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=5000), nullable=False),
    sa.Column('audience', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('appraisal_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('submission_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submission_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year')
    )
    safe_create_table('appraisal_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('doc_key', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('appraisal_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('reviewer_email', sa.String(), nullable=True),
    sa.Column('reviewer_role', sa.String(), nullable=False),
    sa.Column('part_a_score', sa.Numeric(), nullable=False),
    sa.Column('part_b_score', sa.Numeric(), nullable=False),
    sa.Column('part_c_score', sa.Numeric(), nullable=False),
    sa.Column('part_d_score', sa.Numeric(), nullable=False),
    sa.Column('total_score', sa.Numeric(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('section_scores', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('registrar_part_d_score', sa.Numeric(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('appraisal_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('awards',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('award_date', sa.Date(), nullable=True),
    sa.Column('agency', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('book_publications',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('book', sa.String(), nullable=True),
    sa.Column('issn', sa.String(), nullable=True),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('coauthor', sa.String(), nullable=True),
    sa.Column('first_author', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('conferences',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('course_files',
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('course', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('department_activities',
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('activity', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('event_organisation',
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('external_research_projects',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('agency', sa.String(), nullable=True),
    sa.Column('sanction_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('project_status', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('faculty_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('qualification', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('teaching_experience', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('academic_year', sa.String(), nullable=True),
    sa.Column('appraisal_role', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reports_to_registrar', sa.Boolean(), nullable=False),
    sa.Column('reporting_officer_email', sa.String(), nullable=True),
    sa.Column('registrar_email', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    safe_create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=5000), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('form_section_definitions',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=False),
    sa.Column('part', sa.String(), nullable=False),
    sa.Column('section_key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('max_marks', sa.Numeric(), nullable=False),
    sa.Column('storage_table', sa.String(), nullable=True),
    sa.Column('fields', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    safe_create_table('ict_pedagogy',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('quadrant', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('industrial_training',
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('industry_connect',
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('innovative_teaching',
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('ipr_records',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('ipr_date', sa.Date(), nullable=True),
    sa.Column('ipr_status', sa.String(), nullable=True),
    sa.Column('file_no', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('journal_publications',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('journal', sa.String(), nullable=True),
    sa.Column('issn', sa.String(), nullable=True),
    sa.Column('indexing', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('mfa_otps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mfa_token', sa.String(), nullable=False),
    sa.Column('otp_code', sa.String(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mfa_token')
    )
    safe_create_table('module_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appraisal_module_enabled', sa.Boolean(), nullable=False),
    sa.Column('self_appraisal_enabled', sa.Boolean(), nullable=False),
    sa.Column('peer_review_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('non_teaching_appraisals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('self_total', sa.Numeric(), nullable=False),
    sa.Column('ro_total', sa.Numeric(), nullable=False),
    sa.Column('registrar_total', sa.Numeric(), nullable=False),
    sa.Column('vc_total', sa.Numeric(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ro_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registrar_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vc_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('non_teaching_part_a_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('item_key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('max_marks', sa.Numeric(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('self_marks', sa.Numeric(), nullable=True),
    sa.Column('ro_marks', sa.Numeric(), nullable=True),
    sa.Column('registrar_marks', sa.Numeric(), nullable=True),
    sa.Column('vc_marks', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('non_teaching_part_b_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('section_key', sa.String(), nullable=False),
    sa.Column('section_title', sa.String(), nullable=False),
    sa.Column('max_marks', sa.Numeric(), nullable=False),
    sa.Column('parameter_no', sa.Integer(), nullable=False),
    sa.Column('parameter_label', sa.String(), nullable=False),
    sa.Column('ro_rating', sa.Numeric(), nullable=True),
    sa.Column('registrar_rating', sa.Numeric(), nullable=True),
    sa.Column('vc_rating', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('nt_designations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    safe_create_table('nt_workflow_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    safe_create_table('patents',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('patent_date', sa.Date(), nullable=True),
    sa.Column('patent_status', sa.String(), nullable=True),
    sa.Column('file_no', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('placement_mentoring',
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('popular_writings',
    sa.Column('media', sa.String(), nullable=True),
    sa.Column('film', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('products_developed',
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('usage', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('projects_guided',
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('qualification_enhancement',
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('research_guidance',
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('student_name', sa.String(), nullable=True),
    sa.Column('thesis', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('research_projects',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('agency', sa.String(), nullable=True),
    sa.Column('sanction_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('project_status', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('research_proposals',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('agency', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('reviewer_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('reviewer_email', sa.String(), nullable=False),
    sa.Column('reviewer_role', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('self_development',
    sa.Column('program', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('social_contributions',
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('activity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('student_feedback',
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('course_code', sa.String(), nullable=True),
    sa.Column('feedback_1', sa.Numeric(), nullable=False),
    sa.Column('feedback_2', sa.Numeric(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('teaching_process',
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('semester', sa.String(), nullable=True),
    sa.Column('course_code', sa.String(), nullable=True),
    sa.Column('planned_classes', sa.Numeric(), nullable=False),
    sa.Column('conducted_classes', sa.Numeric(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('university_activities',
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('activity', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('form_family', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('hod_score', sa.Numeric(), nullable=True),
    sa.Column('director_score', sa.Numeric(), nullable=True),
    sa.Column('dean_score', sa.Numeric(), nullable=True),
    sa.Column('vc_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('declarations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('part_a_total', sa.Numeric(), nullable=False),
    sa.Column('part_b_total', sa.Numeric(), nullable=False),
    sa.Column('part_c_total', sa.Numeric(), nullable=False),
    sa.Column('part_d_total', sa.Numeric(), nullable=False),
    sa.Column('grand_total', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submission_attempt', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('part_d_status', sa.String(), nullable=False),
    sa.Column('part_d_released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('part_d_released_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['part_d_released_by'], ['faculty_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['faculty_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('nt_workflow_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('staff_email', sa.String(), nullable=True),
    sa.Column('appraisal_role', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['nt_workflow_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_email')
    )
    safe_create_table('nt_workflow_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appraisal_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('staff_email', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_id'], ['non_teaching_appraisals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['nt_workflow_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('nt_workflow_template_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('designation_id', sa.UUID(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['designation_id'], ['nt_designations.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['nt_workflow_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('hod_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['faculty_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_table('nt_workflow_instance_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('reviewer_email', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['nt_workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nt_workflow_instance_steps')
    op.drop_table('hod_assignments')
    op.drop_table('nt_workflow_template_steps')
    op.drop_table('nt_workflow_instances')
    op.drop_table('nt_workflow_assignments')
    op.drop_table('departments')
    op.drop_table('declarations')
    op.drop_table('university_activities')
    op.drop_table('teaching_process')
    op.drop_table('student_feedback')
    op.drop_table('social_contributions')
    op.drop_table('self_development')
    op.drop_table('reviewer_snapshots')
    op.drop_table('research_proposals')
    op.drop_table('research_projects')
    op.drop_table('research_guidance')
    op.drop_table('qualification_enhancement')
    op.drop_table('projects_guided')
    op.drop_table('products_developed')
    op.drop_table('popular_writings')
    op.drop_table('placement_mentoring')
    op.drop_table('patents')
    op.drop_table('password_reset_tokens')
    op.drop_table('nt_workflow_templates')
    op.drop_table('nt_designations')
    op.drop_table('non_teaching_part_b_ratings')
    op.drop_table('non_teaching_part_a_items')
    op.drop_table('non_teaching_appraisals')
    op.drop_table('module_config')
    op.drop_table('mfa_otps')
    op.drop_table('journal_publications')
    op.drop_table('ipr_records')
    op.drop_table('innovative_teaching')
    op.drop_table('industry_connect')
    op.drop_table('industrial_training')
    op.drop_table('ict_pedagogy')
    op.drop_table('form_section_definitions')
    op.drop_table('feedback')
    op.drop_table('faculty_profiles')
    op.drop_table('external_research_projects')
    op.drop_table('event_organisation')
    op.drop_table('department_activities')
    op.drop_table('course_files')
    op.drop_table('conferences')
    op.drop_table('book_publications')
    op.drop_table('awards')
    op.drop_table('appraisal_snapshots')
    op.drop_table('appraisal_reviews')
    op.drop_table('appraisal_documents')
    op.drop_table('appraisal_config')
    op.drop_table('announcements')
    op.drop_table('alumni_engagement')
    op.drop_table('acr_scores')
    # ### end Alembic commands ###
